name: Build Docker
on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to proget
        uses: docker/login-action@v1
        with:
          registry: http://localhost:8080
          username: ${{ secrets.PROGET_USER }}
          password: ${{ secrets.PROGET_PASS }}

      - name: Build
        run: |
          docker build . --file Dockerfile --tag localhost:8080/images/apps/ps-hello:latest
          docker push localhost:8080/images/apps/ps-hello:latest
