name: Build Docker
on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to proget
        uses: docker/login-action@v1
        with:
          registry: https://proget.pollusmoveis.com.br/docker
          username: ${{ secrets.PROGET_USER }}
          password: ${{ secrets.PROGET_PASS }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: proget.pollusmoveis.com.br/docker/apps/ps-hello:latest
